
trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- checkout: self
  submodules: true

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'

- task: Npm@1
  displayName: 'npm run bootstrap'
  inputs:
    command: 'custom'
    customCommand: 'run bootstrap'

- task: Npm@1
  displayName: 'npm run tsc'
  inputs:
    command: 'custom'
    customCommand: 'run tsc'

- task: Npm@1
  displayName: 'npm run build'
  env:
    REACT_APP_BUILD_ID: $(Build.BuildNumber)
  inputs:
    command: 'custom'
    workingDir: 'app/web'
    customCommand: 'run build'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs' #'serviceEndpoint' Options: serviceEndpoint, inputs
    #serverEndpoint: # Required when credentialsOption == ServiceEndpoint
    serverUrl: ftps://server232.campusspeicher.de # Required when credentialsOption == Inputs
    username: h136763 # Required when credentialsOption == Inputs
    password: $(ftp_pw) # Required when credentialsOption == Inputs
    rootDirectory: 
    filePatterns: 'app/web/build/**' 
    remoteDirectory: '/httpdocs/' 
    #clean: false 
    #cleanContents: false # Required when clean == False
    #preservePaths: false 
    trustSSL: true 